name: Trigger auto deployment for book-sharing-app-backend

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/book-sharing-app-backend-AutoDeployTrigger-0d59b511-0814-4695-b810-21ac6e473143.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.BOOKSHARINGAPPBACKEND_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.BOOKSHARINGAPPBACKEND_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.BOOKSHARINGAPPBACKEND_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: 
          registryUsername: ${{ secrets.BOOKSHARINGAPPBACKEND_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.BOOKSHARINGAPPBACKEND_REGISTRY_PASSWORD }}
          containerAppName: book-sharing-app-backend
          resourceGroup: book-sharing-app
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


